Feat: implement new command EXZPOPMAX and EXZPOPMIN.
alibaba/TairZset pull request #14
Opened 2022-07-27 11:00 UTC by RinChanNOWWW

Signed-off-by: RinChanNOWWW <hzy427@gmail.com>

relate issue: #4

2022-08-03 08:45 UTC, chenyang8094 commented on src/tairzset.c
> +        zln = (where == POP_MAX ? zsl->tail :
format

2022-08-03 08:48 UTC, chenyang8094 commented on src/tairzset.c
> +    if (type == REDISMODULE_KEYTYPE_EMPTY || key == NULL) {
I think `key == NULL` is no need.

2022-08-03 08:52 UTC, chenyang8094 requested changes
LGTM

2022-08-03 09:39 UTC, RinChanNOWWW commented on src/tairzset.c
> +    if (type == REDISMODULE_KEYTYPE_EMPTY || key == NULL) {
I see.

2022-08-04 01:21 UTC, chenyang8094 approved these changes

2022-08-04 01:21 UTC, merged