Feat: implement new command EXZMSCORE
alibaba/TairZset pull request #5
Opened 2022-06-16 12:16 UTC by RinChanNOWWW

Signed-off-by: RinChanNOWWW <hzy427@gmail.com>

# Summary

### EXZMSCORE
> EXZMSCORE key member [member ...]
> time complexity：O(N) where N is the number of members being requested.
### Command Description:

Returns the scores associated with the specified members in the sorted set stored at key. For every member that does not exist in the sorted set, a nil value is returned.

### Return value

Array reply: list of scores or nil associated with the specified member values (a double precision floating point number), represented as strings.

2022-06-16 12:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/alibaba/TairZset?pullRequest=5) <br/>All committers have signed the CLA.

2022-06-17 01:03 UTC, chenyang8094 requested changes

2022-06-17 01:03 UTC, chenyang8094 commented on tests/tairzset.tcl
> +    test "EXZMSCORE retrieve requires one or more members" {
测试中加一些多维的分数测试

2022-06-17 01:03 UTC, chenyang8094 commented on CMDDOC.md
> +Array reply: list of scores or nil associated with the specified member values (a double precision floating point number), represented as strings.
```suggestion
Array reply: list of scores or nil associated with the specified member values (multiple double-precision floating-point numbers separated by #), represented as strings.
```

2022-06-17 03:37 UTC, RinChanNOWWW commented on tests/tairzset.tcl
> +    test "EXZMSCORE retrieve requires one or more members" {
Done.

2022-06-17 05:58 UTC, chenyang8094 approved these changes
LGTM

2022-06-17 06:04 UTC, merged