Feat: implement new command EXZRANDMEMBER.
alibaba/TairZset pull request #6
Opened 2022-06-19 02:51 UTC by RinChanNOWWW

Signed-off-by: RinChanNOWWW <hzy427@gmail.com>

# Summary

related issues: #4

Implementation reference: Redis 6.2

## Command Description

### EXZRANDMEMBER
> EXZRANDMEMBER key [ count [WITHSCORES]]
> time complexity：O(N) where N is the number of elements returned.

#### Command Description:

When called with just the key argument, return a random element from the sorted set value stored at key.

If the provided count argument is positive, return an array of distinct elements. The array's length is either count or the sorted set's cardinality (EXZCARD), whichever is lower.

If called with a negative count, the behavior changes and the command is allowed to return the same element multiple times. In this case, the number of returned elements is the absolute value of the specified count.

The optional WITHSCORES modifier changes the reply so it includes the respective scores of the randomly selected elements from the sorted set.

#### Return value

Bulk string reply: without the additional count argument, the command returns a Bulk Reply with the randomly selected element, or nil when key does not exist.

Array reply: when the additional count argument is passed, the command returns an array of elements, or an empty array when key does not exist. If the WITHSCORES modifier is used, the reply is a list elements and their scores from the sorted set.

2022-06-20 11:42 UTC, chenyang8094 requested changes

2022-06-20 11:42 UTC, chenyang8094 commented on src/tairzset.c
> +/* EXZRANDMEMBER key [ count [WITHSCORES]] */
```suggestion
/* EXZRANDMEMBER key [count [WITHSCORES]] */
```

2022-06-20 11:44 UTC, RinChanNOWWW commented on src/tairzset.c
> +/* EXZRANDMEMBER key [ count [WITHSCORES]] */
Done.

2022-06-20 11:46 UTC, chenyang8094 approved these changes

2022-06-20 11:49 UTC, merged

2022-06-21 02:22 UTC, chenyang8094 commented
LGTM